### ISSUE TITLE
Deck Model Rework

### ISSUE THREAD

**Issue by kensonjohnson** [kensonjohnson/three-bet#16]
**Is your feature request related to a problem? Please describe.**

The Deck model doesn't currently provide some helper properties and exposes access to all of it's property values.

**Describe the solution you'd like**

- Make `cards` and `discardPile` private.
- Add getter for `size` property
- Add method to refresh the deck

**Comment by christopherkeim** [comment]
What is the desired state of the deck once it is refreshed - what does a refreshed deck look like?
